export const ProductService = {
        getProductsData() {
            return [
                {
                    id: '1000',
                    title: 'f230fh0g3',
                    content: 'Bamboo Watch',
                    start_plan: 'Product Description',
                    image: 'bamboo-watch.jpg',
                    price: 65,
                    category: 'Accessories',
                    quantity: 24,
                    is_completed: true,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1001',
                    title: 'nvklal433',
                    content: 'Black Watch',
                    start_plan: 'Product Description',
                    image: 'black-watch.jpg',
                    price: 72,
                    category: 'Accessories',
                    quantity: 61,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1002',
                    title: 'zz21cz3c1',
                    content: 'Blue Band',
                    start_plan: 'Product Description',
                    image: 'blue-band.jpg',
                    price: 79,
                    category: 'Fitness',
                    quantity: 2,
                    is_completed: false,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1003',
                    title: '244wgerg2',
                    content: 'Blue T-Shirt',
                    start_plan: 'Product Description',
                    image: 'blue-t-shirt.jpg',
                    price: 29,
                    category: 'Clothing',
                    quantity: 25,
                    is_completed: true,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1004',
                    title: 'h456wer53',
                    content: 'Bracelet',
                    start_plan: 'Product Description',
                    image: 'bracelet.jpg',
                    price: 15,
                    category: 'Accessories',
                    quantity: 73,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1005',
                    title: 'av2231fwg',
                    content: 'Brown Purse',
                    start_plan: 'Product Description',
                    image: 'brown-purse.jpg',
                    price: 120,
                    category: 'Accessories',
                    quantity: 0,
                    is_completed: null,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1006',
                    title: 'bib36pfvm',
                    content: 'Chakra Bracelet',
                    start_plan: 'Product Description',
                    image: 'chakra-bracelet.jpg',
                    price: 32,
                    category: 'Accessories',
                    quantity: '2024-11-27',
                    is_completed: false,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1007',
                    title: 'mbvjkgip5',
                    content: 'Galaxy Earrings',
                    start_plan: 'Product Description',
                    image: 'galaxy-earrings.jpg',
                    price: 34,
                    category: 'Accessories',
                    quantity: 23,
                    is_completed: true,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1008',
                    title: 'vbb124btr',
                    content: 'Game Controller',
                    start_plan: 'Product Description',
                    image: 'game-controller.jpg',
                    price: 99,
                    category: 'Electronics',
                    quantity: 2,
                    is_completed: false,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1009',
                    title: 'cm230f032',
                    content: 'Gaming Set',
                    start_plan: 'Product Description',
                    image: 'gaming-set.jpg',
                    price: 299,
                    category: 'Electronics',
                    quantity: 63,
                    is_completed: true,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1010',
                    title: 'plb34234v',
                    content: 'Gold Phone Case',
                    start_plan: 'Product Description',
                    image: 'gold-phone-case.jpg',
                    price: 24,
                    category: 'Accessories',
                    quantity: 0,
                    is_completed: null,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1011',
                    title: '4920nnc2d',
                    content: 'Green Earbuds',
                    start_plan: 'Product Description',
                    image: 'green-earbuds.jpg',
                    price: 89,
                    category: 'Electronics',
                    quantity: 23,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1012',
                    title: '250vm23cc',
                    content: 'Green T-Shirt',
                    start_plan: 'Product Description',
                    image: 'green-t-shirt.jpg',
                    price: 49,
                    category: 'Clothing',
                    quantity: 74,
                    is_completed: true,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1013',
                    title: 'fldsmn31b',
                    content: 'Grey T-Shirt',
                    start_plan: 'Product Description',
                    image: 'grey-t-shirt.jpg',
                    price: 48,
                    category: 'Clothing',
                    quantity: 0,
                    is_completed: null,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1014',
                    title: 'waas1x2as',
                    content: 'Headphones',
                    start_plan: 'Product Description',
                    image: 'headphones.jpg',
                    price: 175,
                    category: 'Electronics',
                    quantity: '2024-11-17',
                    is_completed: false,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1015',
                    title: 'vb34btbg5',
                    content: 'Light Green T-Shirt',
                    start_plan: 'Product Description',
                    image: 'light-green-t-shirt.jpg',
                    price: 49,
                    category: 'Clothing',
                    quantity: 34,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1016',
                    title: 'k8l6j58jl',
                    content: 'Lime Band',
                    start_plan: 'Product Description',
                    image: 'lime-band.jpg',
                    price: 79,
                    category: 'Fitness',
                    quantity: 12,
                    is_completed: true,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1017',
                    title: 'v435nn85n',
                    content: 'Mini Speakers',
                    start_plan: 'Product Description',
                    image: 'mini-speakers.jpg',
                    price: 85,
                    category: 'Clothing',
                    quantity: 42,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1018',
                    title: '09zx9c0zc',
                    content: 'Painted Phone Case',
                    start_plan: 'Product Description',
                    image: 'painted-phone-case.jpg',
                    price: 56,
                    category: 'Accessories',
                    quantity: 41,
                    is_completed: true,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1019',
                    title: 'mnb5mb2m5',
                    content: 'Pink Band',
                    start_plan: 'Product Description',
                    image: 'pink-band.jpg',
                    price: 79,
                    category: 'Fitness',
                    quantity: 63,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1020',
                    title: 'r23fwf2w3',
                    content: 'Pink Purse',
                    start_plan: 'Product Description',
                    image: 'pink-purse.jpg',
                    price: 110,
                    category: 'Accessories',
                    quantity: 0,
                    is_completed: null,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1021',
                    title: 'pxpzczo23',
                    content: 'Purple Band',
                    start_plan: 'Product Description',
                    image: 'purple-band.jpg',
                    price: 79,
                    category: 'Fitness',
                    quantity: 6,
                    is_completed: false,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1022',
                    title: '2c42cb5cb',
                    content: 'Purple Gemstone Necklace',
                    start_plan: 'Product Description',
                    image: 'purple-gemstone-necklace.jpg',
                    price: 45,
                    category: 'Accessories',
                    quantity: 62,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1023',
                    title: '5k43kkk23',
                    content: 'Purple T-Shirt',
                    start_plan: 'Product Description',
                    image: 'purple-t-shirt.jpg',
                    price: 49,
                    category: 'Clothing',
                    quantity: 2,
                    is_completed: false,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1024',
                    title: 'lm2tny2k4',
                    content: 'Shoes',
                    start_plan: 'Product Description',
                    image: 'shoes.jpg',
                    price: 64,
                    category: 'Clothing',
                    quantity: 0,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1025',
                    title: 'nbm5mv45n',
                    content: 'Sneakers',
                    start_plan: 'Product Description',
                    image: 'sneakers.jpg',
                    price: 78,
                    category: 'Clothing',
                    quantity: 52,
                    is_completed: true,
                    end_plan: '2024-11-02'
                },
                {
                    id: '1026',
                    title: 'zx23zc42c',
                    content: 'Teal T-Shirt',
                    start_plan: 'Product Description',
                    image: 'teal-t-shirt.jpg',
                    price: 49,
                    category: 'Clothing',
                    quantity: '2024-11-13',
                    is_completed: false,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1027',
                    title: 'acvx872gc',
                    content: 'Yellow Earbuds',
                    start_plan: 'Product Description',
                    image: 'yellow-earbuds.jpg',
                    price: 89,
                    category: 'Electronics',
                    quantity: 35,
                    is_completed: true,
                    end_plan: '2024-11-13'
                },
                {
                    id: '1028',
                    title: 'tx125ck42',
                    content: 'Yoga Mat',
                    start_plan: 'Product Description',
                    image: 'yoga-mat.jpg',
                    price: 20,
                    category: 'Fitness',
                    quantity: 15,
                    is_completed: true,
                    end_plan: '2024-11-27'
                },
                {
                    id: '1029',
                    title: 'gwuby345v',
                    content: 'Yoga Set',
                    start_plan: 'Product Description',
                    image: 'yoga-set.jpg',
                    price: 20,
                    category: 'Fitness',
                    quantity: 25,
                    is_completed: true,
                    end_plan: '2024-11-17'
                }
            ];
        },


        getProducts() {
            return Promise.resolve(this.getProductsData());
        },

    };

    